# Comments are provided throughout this file to help you get started.
# If you need more help, visit the Docker compose reference guide at
# https://docs.docker.com/compose/compose-file/

# Here the instructions define your application as two services called "todo-app" and “todo-database”
# The service “todo-app” is built from the Dockerfile in the /app directory,
# and the service “todo-database” uses the official MongoDB image 
# from Docker Hub - https://hub.docker.com/_/mongo. 
# You can add other services your application may depend on here.

services:
  neuron-node-app:
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - neuron-mongo-database
    environment:
      NODE_ENV: production
    ports:
      - 8002:8001
      - 35729:35729
    develop:
      watch:
        - path: ./package.json
          action: rebuild
        - path: ./
          target: /usr/src/app
          action: sync
  neuron-mongo-database:
    image: mongo:6
    volumes: 
      - database:/data/db
    ports:
      - 27017:27017
    #environment:
      #MONGO_INITDB_ROOT_USERNAME: root
      #MONGO_INITDB_ROOT_PASSWORD: example
      #MONGO_INITDB_DATABASE: NEURON
volumes:
  database: 
    name: neuron