openapi: '3.0.2'
info:
  title: NEURON
  version: '1.0'
servers:
  - url: https://neuron.onrender.com
    description: PROD server
  - url: http://localhost:8001
    description: Debug server
components:
  securitySchemes:
    NeuronUserName:
      type: apiKey
      in: header
      name: neuron_username
    NeuronAuthToken:
      type: apiKey
      in: header
      name: neuron_authtoken
    
paths:
  /version:
    get:
      operationId: version
      security: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
  /newuser:
    post:
      operationId: newuser
      security: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
              required:
                - "username"
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  authtoken:
                    type: string
                required:
                  - "authtoken"
            
security:
  - NeuronUserName: []
    NeuronAuthToken: []