openapi: '3.0.2'
info:
  title: NEURON
  version: '1.0'
servers:
  - url: https://neuron.onrender.com
    description: PROD server
  - url: http://localhost:8001
    description: Debug server
components:
  securitySchemes:
    NeuronUserId:
      type: apiKey
      in: header
      name: neuron_userid
    NeuronAuthToken:
      type: apiKey
      in: header
      name: neuron_authtoken
paths:
  /version:
    get:
      operationId: version
      security: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
security:
  - NeuronUserId: []
    NeuronAuthToken: []